# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
locale            : "vi"
title             : Đỗ Đình Sĩ
email             : sidodinh@gmail.com
description       : "Blog cá nhân - Senior Mobile developer"
baseurl           :
url               : "https://sidd88.github.io"
twitter_username  : sidd88
github_username   : sidd88
repository        : "sidd88/sidd88.github.io"
words_per_minute  : 200

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - _pages
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
